### ISSUE TITLE
2 Way audio support, how to add as a new feature?

### ISSUE THREAD

**Issue by Skinah** [Skinah/IpCamera#1]
Needing some help on direction to take for supporting 2 way audio and what the best approach is before wasting time looking at a method only to hit a roadblock and finding all the time was wasted. Can someone help guide me as to which way is best and the limitations of each method and also how the feature should work before I start writing the code to add this feature? thanks for any comments.

Why add the feature...
Doorbell use or baby monitor are two use cases.
Doorbell: Would be handy to talk to someone at your door with a picture to confirm their ID and to give instructions before you unlock the door to let them drop a parcel off at your house when you are not home. Point to point would work for this if you press a button on a single tablet to take over the audio from the camera.
Baby Monitor:  1 way audio will be useful to play white noise or lullaby or even an audio book via  MP3. Also handy to 2 way talk if a child gets out of bed in the middle of the night. Point to point would work for this.

Protocols to look at...
JsSip/SIPml5: Appears to only do point to point so 1 camera can not broadcast to multiple tablets.
Freeswitch as SIP proxy:  Appears to only do point to point so 1 camera can not broadcast to multiple tablets.
WebRTC: Not sure what this can do yet.

**Comment by DubZyy** [comment]
Hi Skinah,

at this moment I cant help much because I'm also learning in WebRTC and SIP. While my investigation in the past I found a project on youtube (https://www.youtube.com/watch?v=U09WDGR2jQo) which is described in google docs: https://docs.google.com/document/d/1e7U_WM1jSo0wgMX5RdpN0eN6p9TWadGYHqWf6yR2JZM/mobilebasic

but still no time to read more about that. I think WebRTC would solve all the things including 2 way audio with "unlimited" clients, not only p2p.
