### ISSUE TITLE
Dahua Output control 

### ISSUE THREAD

**Issue by kristo2301** [Skinah/IpCamera#15]
**Hi Matt, 
As mentioned on forum, please add control of output:
Output 1 ON:**
/cgi-bin/configManager.cgi?action=setConfig&AlarmOut[0].Mode=1
**Output 2 ON:**
/cgi-bin/configManager.cgi?action=setConfig&AlarmOut[1].Mode=1

**Output 1 OFF:**
/cgi-bin/configManager.cgi?action=setConfig&AlarmOut[0].Mode=2
**Output 2 OFF:**
/cgi-bin/configManager.cgi?action=setConfig&AlarmOut[1].Mode=2

**Expected answer to confirm command:**
OK

**Output status check:**
/cgi-bin/alarm.cgi?action=getOutState

**answer:**
result=0 **//no alarm - all off**
result=1 **//alarm ch. 1**
result=2 **//alarm ch. 2**
result=3 **//alarm ch. 1 & alarm ch. 2 - all on**

**Comment by Skinah** [comment]
These URL's do not have the channel for using behind a NVR, it is possible that the function does not work from behind a NVR but if you could look into it and test it please.
It may be something as simple as adding &channel=0 to the url if it is standalone camera or a number for the channel the camera is connected to the NVR.

Since this appears to be the same as HIKVISION which has working switchable outputs, it can share the same channels to reuse code.

**Comment by kristo2301** [comment]
OK
Output status check:  working ok 
/cgi-bin/alarm.cgi?action=getOutState&channel=0
but set channel state not
 eaven if you have cam behind NVR you can connect to them directly by using different IP and this issue will not exist

**Comment by Skinah** [comment]
Ok I have added my own version of this and will be in the next build:

Turning the switch on will force the alarm
/cgi-bin/configManager.cgi?action=setConfig&AlarmOut[0].Mode=1

Turning the switch off will return it to automatic mode as people may have setup the alarm outputs to respond the events in the cameras setup..
/cgi-bin/configManager.cgi?action=setConfig&AlarmOut[0].Mode=0

I think this is a better way if it works at turning off the alarm when going back to the auto mode. Let me know if the alarm refuses to turn back off.
