### ISSUE TITLE
Dahua Varifocal zoom & autofocus

### ISSUE THREAD

**Issue by kristo2301** [Skinah/IpCamera#17]
After review of few forums i can confrim that with Vari-Focal cams PTZ will not work
Only solution is to:

/cgi-bin/devVideoInput.cgi?action=adjustFocus&focus=0&zoom=1

after first run zoom will go to position
after second run without zoom value change focus will adjust automaticly
Run can be with small delay
Zoom have to be form 0 to 1

Addtionally to get status of Zoom and Focus:

/cgi-bin/devVideoInput.cgi?action=getFocusStatus

answer:

status.Focus=0.888506
status.FocusMotorSteps=3480
status.Status=Normal
status.Zoom=0.600000
status.ZoomMotorSteps=1350

Autofocus switch will be also useful:

/cgi-bin/devVideoInput.cgi?action=autoFocus

**Comment by Skinah** [comment]
This one is a LOT of work as I would need to work out the best way to switch from ONVIF controls to brand API controls at a programming level, at the same time leave the ability to support more than just ABSOLUTE movement. At a user level I would prefer to hard switch over to the API instead of ONVIF whenever the API option exists. This is due to a long delay from when I tell the camera to move to when it actually moves with ONVIF with my camera. I suspect the API will be far faster.
Low priority for me as I don't move the camera much currently and the delay is not important with absolute movement.

**Comment by Skinah** [comment]
Does this url change the varifocal zoom without changing the focus? Is it possible to change the zoom only and keep focus on auto?

/cgi-bin/devVideoInput.cgi?action=adjustFocus&zoom=1

**Comment by kristo2301** [comment]
I started testing of this function and need more time to find good flow to
get it working.
If you change zoom it's impacting focus and what is strange autofocus is
not doing adjustment

pt., 8 lut 2019, 09:21: Skinah <notifications@github.com> napisał(a):

**Comment by Skinah** [comment]
I have just updated the Onvif library and a lot more is now possible via onvif. Test to see if it can be done inside the free program called 'onvif device manager' and if it can be done in there, then it should be possible with enough coding in the binding via the new onvif library.

**Comment by Skinah** [comment]
I Just added Onvif presets and this may work for you if your camera can set and recall presets. Closing this down as there are 2 ways to move a camera with Onvif in recent builds. If these dont work and the API fails to be reliable there is not much reason to leave this issue open.
