### ISSUE TITLE
FR: Ringbuffer

### ISSUE THREAD

**Issue by cribskip** [Skinah/IpCamera#26]
Hi,

I've got a feature request and maybe you think it's sensible to implement in the binding:
- Save a copy of the stream/image in a configurable ring buffer
- On triggering, provide a object which points to the buffer - configurable seconds before the event which may be saved to a file

Best regards & keep up the wonderful work :-)
Sascha

**Comment by Skinah** [comment]
Can you give an example use case for this? Knowing more details on how you will use a feature helps to flesh out the details.
I have been considering a feature that may be the same idea. Recently I introduced the animated GIF feature and I think that will cover my use case which is showing the last motion alarm in a sitemap without increasing the CPU load of the Openhab server. The one aspect the feature lacks that I was wanting was a configurable prefetch setting, to show what movement occurred just before the alarm was triggered... I'm guessing that is what you want? A similar feature so that it can provide images from BEFORE the triggering event?

**Comment by cribskip** [comment]
> I'm guessing that is what you want?
Exactly. Just like in [Motion's pre_capture](https://motion-project.github.io/motion_config.html#pre_capture). I'm currently setting up motion to do the motion detection and triggering, then attaching the IP cam binding to it.

**Comment by Skinah** [comment]
This presents some issues because I feel the only way to do precapture/preroll would be to use snapshots as the source instead of the RTSP source currently used and to constantly be fetching a snapshot every second. Not sure if all cameras can handle fetching every second, but all cameras should be able to handle a RTSP stream. 
I also don't like the idea of a non stop stream hitting the Openhab server causing a load... The direction I have been heading is to have zero CPU, network and disk activity from the binding unless you require something from the binding and only then it will place a load on these things when required and then automatically stops when complete. This is to give the binding a unique place (niche) when compared to Motion or any of the other video packages which can be used to provide certain features.

It may be possible to use RTSP as the default source unless a config called "GIF_PREROLL" was more than 0, then the binding auto switches over to using snapshots seamlessly handling the differences behind the scenes. 

The second issue is the config item  FFMPEG_GIF_OUT_ARGUMENTS
When using RTSP as the source it may need a different value to when using Snapshots as the source. This is probably a minor issue easily sorted.

There is a user already doing this with scripts and snapshots here..
https://community.openhab.org/t/blue-iris-integration-http-binding-rest-api/10838/26

**Comment by cribskip** [comment]
Ok, I see. Good points!
I'll resort to the solution you mentioned, seems sensible.

Thank you! :-)

**Comment by Skinah** [comment]
I’ll leave this open as it is a good feature request and something I am keen to add at some stage.

**Comment by Skinah** [comment]
I have done some thinking on how to best implement this, how does this sound?
Example is if you want an animated GIF that is 6 seconds before the doorbell is pushed and to include only 1 second after the doorbell button is pushed to have a minimal delay from when the button is pushed to when you get notified.

Two configs are then setup:
GIF_PREROLL = 6
GIF_POSTROLL = 1

The camera stores the 7 snapshots in a FIFO buffer and can create the GIF the same way they are made now only they come from snapshots and not a stream. The only complication is when you poll/fetch a snapshot less often then every second it will confuse users as they expect it to be in seconds but it is actually 6*poll rate. Going to be a bit of a pain to explain this in a readme file and to top it off it behaves differently when GIF_PREROLL = 0 as it then uses the current method of using the stream as the source which caters to people who wish to have the snapshots turned off.

**Comment by Skinah** [comment]
Successfully added this feature and just testing it now so closing this topic. Code already pushed to github.
