### ISSUE TITLE
UpdateGif function includes images not part of the actual sequence

### ISSUE THREAD

**Issue by lainsan** [Skinah/IpCamera#38]
The GIF file created may include images in the sequence, which are not part of the current stream. 
In the example attached you can observe this behavior:
The image is from today, Oct 25th, and includes one or more images from Oct 22nd (See timestamp top left).

The effect may be triggered due to changing the number of pre-roll/post-roll images in the thing config - most likely when reducing the number of pictures.

**Comment by lainsan** [comment]
![1796749B-2E6F-474D-BB3C-FE5F3CEEA9A6](https://user-images.githubusercontent.com/56224339/67577146-345d2d00-f740-11e9-995b-487265dbb29b.gif)

**Comment by lainsan** [comment]
Seems like I cannot upload the example from my mobile. Will provide the example when home again.

**Comment by lainsan** [comment]
While not having looked at the source code, from testing i assume something like this is happening:
- user enters number of images to go into GIF
- Binding stores upon updateGif number of images according to frequency and number of GIFs in a folder
- ffmpeg is called to convert all images in folder into GiF.

If now number of images is reduced in config less images are stored (overwritten) in the folder. Any images >new number still remains and is also being converted in the GIF - although not belonging to the sequence. FGmpeg always seems to take all images - so the GIF always has the same length, it has just less images updated (by the binding).

**Comment by Skinah** [comment]
This happens on my setup after it has been running a while so I reboot it once a week and all is good. Not sure why it works for days and then a glitch occurs that means the last snapshot does not get updated. Have not looked into it yet but it may be that a ffmpeg instance crashes and does not complete whilst still having the last snapshot open. Since the file is still open the binding can not overwrite it. If you know how to use Linux then it would be helpful to look at the folder where ffmpeg uses and look at the snapshot files and see if it is a permission issue or if the file is still in use.

Your assumption is how it works and in my case I do not change the number of snapshots and it still has an issue. Since I use a ram drive (tmpfs) a simple reboot fixes it for me as the whole folder gets recreated on reboot.

**Comment by lainsan** [comment]
Will have a look at it.

Do i understand correctly, that ipcamera first stores a set of JPEG images from which it then asks FFMPEG to create the GIF? If yes, where does ipcamera store the (temporary) images - in the same (target) folder as the GIF itself?

**Comment by lainsan** [comment]
Here's what i found:
- i currently have set my things to preroll 3, postroll 18, every 1000ms
- these total to 21 snapshots, numbered from 0-20
- they overwrite any existing snapshots named snapshot1, [...], snapshot20.jpg

I once had the settings set to preroll 3, postroll 21 - totalling to 24 snapshots.
Snapshot21.jpg, snapshot22.jpg, snapshot23.jpg still exist in the directory (see directory listing attached, have a look at the timestamp).

![dir_listing](https://user-images.githubusercontent.com/56224339/68535863-6037ff80-0349-11ea-8c3a-e561c355cce3.JPG)

Any time i invoke UpdateGif, the first 21 snapshots get updated - however, FFMPEG will always use the total 24 snapshots to create the GIF.

It's easy to fix for me now by cleaning up the directory manually.

But anytime someone reduces the total number of snapshots created for the GIF, they might experience the same issue.

Is there any chance, when you call FFMPEG in the binding, to have logic like FFPMPEG only include as many snapshots as current setting of GIF_PREROLL PLUS GIF_POSTROLL will update?

**Comment by Skinah** [comment]
Thanks for the extra info, I agree this should be changed to make life easier when changing the setting.

**Comment by lainsan** [comment]
I am also seeing now the behaviour you described:
I have left the numbers of images to be taken into the GIF at 3 pre + 18 post roll.
However, after some time it does not seem to update a selection of images. Strange.

![Capture](https://user-images.githubusercontent.com/56224339/69097491-ef829880-0a56-11ea-84fb-757beabb676e.JPG)

An easy fix might be to just clean-up snapshots every once in a while. Might do that independently with a cron job.

**Comment by Skinah** [comment]
Planning on taking a look at this over Christmas break as it is the only issue on my setup, if you capture any debug logs of this that would help. I ruled out permissions causing this but have not dived into the code as prefer to fix the root reason and not a work around.

**Comment by Skinah** [comment]
I just uploaded a new build with changes to how the snapshots are stored in a buffer. It won’t fix the issue of when u change the settings without rebooting but I am hoping it stops the old snapshots from being an issue. Will be looking at this more over the next week.

**Comment by lainsan** [comment]
Still testing this, working well now if assessed correctly.
I do see some strange behaviours, but they seem to derive from my other problem of cameras not updating.
Will get back in a bit to re-confirm it's working.

**Comment by Skinah** [comment]
I looked at trying to solve the extra snapshots when you modify the number of pre and post roll pictures and I could not find a way I liked.

-frames:v (preroll + postroll)
This limits the number of frames used on the OUTPUT arguments but with the fast forward filter I use as default it turns 8 pictures into only 2 due to the 4x playback speed.

You can also do a start number to not start at 0 but there is no -end_number equalient. 
-start_number 837

Seems the only way is to delete the files which is something I would rather stay away from. At this point I would prefer people clean up the files manually or use a tmpfs folder and use a reboot to solve the problem which should now only be if you adjust the pre and postroll values.

Closing this for now.
