### ISSUE TITLE
Authentication not working for ONVIF camera.

### ISSUE THREAD

**Issue by militanz** [Skinah/IpCamera#53]
I’ve configured a generic ONVIF camera like this:

```
# cat ipcamera.things

Thing ipcamera:ONVIF:003
[
    IPADDRESS="10.18.12.232",
    PASSWORD="passwordgoeshere",
    USERNAME="admin",
    ONVIF_PORT=8999,
    PORT=80,
    UPDATE_IMAGE=false,
    SERVER_PORT=-1,
    FFMPEG_OUTPUT="/tmpfs/camera3/"
]

```
Since it’s not working, I’ve done a tcpdump to understand why and I’ve noticed that OH is not using username and password when talking to the camera, and therefore it’s getting a “401 Unauthorized”. Just to be sure I’ve installed and ONVIF tool on my machine, and I was able to see the stream. Did a capture and it’s doing Basic authentication as expected.

So it looks like even if I’ve configured username and password it’s not considering them. I’ve tested with PaperUI and then with the config file, same result.

In the capture "onvif_working_http.txt" you can see in line 831 that my laptop is using credentials when doing a POST to /onvif/device_service.
In the capture "onvif_not_working_http.txt" you can see in line 88 that the OH server is not sending credentials when doing the same POST.

[onvif_working_http.txt](https://github.com/Skinah/IpCamera/files/4515514/onvif_working_http.txt)
[onvif_not_working_http.txt](https://github.com/Skinah/IpCamera/files/4515517/onvif_not_working_http.txt)

**Comment by Skinah** [comment]
Camera should reply like this and the first error should be ignored and the Library should then repeat the last request with the correct header:

HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="gSOAP Web Service"

The onvif lib should reply from then on with this header...
Authorization: Basic hashHereContainingYourUserPass*(^*&$%

That is why it is not working, as the Authorization header is missing. Why I do not know, as I use an external ONVIF library and you would need to report the issue at the librarys GitHub here.

https://github.com/RootSoft/ONVIF-Java

The only thing I can suggest is that you ensure the UTC time is correct by checking the timezone and time is the exact same on your openhab server and your camera. The ONVIF spec outlines that if the UTC time does not match then that is a cause to refuse communications.

If I ever get really bored, I could re do all the work of the library and implement my own classes but I don't see that happening anytime soon unless another user steps up and helps out. It is probably 160 hours of work. Cheaper to buy a camera that works out of the box.

The only thing that ONVIF is needed for is to move a PTZ camera.

**Comment by Skinah** [comment]
The next build of the binding which will get released once the bugs are squashed over the next few days, has an all new ONVIF library which may solve some auth issues. There may be more than 1 way to do auths with ONVIF, however the latest spec is to use a DIGEST in the XML and not to use http based auths. If the newer binding does not work on your camera I am probably not keen to add the method that looks like this due to it being a security flaw. Anyone looking at the traffic can steal the password in seconds, so to add that header seriously lower security and I see it as a bug.

```
WWW-Authenticate: Basic realm="gSOAP Web Service"
Authorization: Basic hashHereContainingYourUserPass*(^*&$%
```

Update the cameras firmware and hopefully it uses the more standard digest XML/soap based method that ONVIF recommends.
